### ISSUE TITLE
When flashing lk2nd-edt 19.0 the system does not boot

### ISSUE THREAD

**Issue by progzone122** [progzone122/lk2nd-xiaomi-daisy-sakura-prebuild#1]
https://gist.github.com/progzone122/d414579aee2d62ad045ffdf034e0e18d?permalink_comment_id=5329186#gistcomment-5329186

**Comment by progzone122** [comment]
It would be nice if you could provide information about the screen and sensor from HW Info

**Comment by progzone122** [comment]
And tell me in detail how exactly it doesn't load, preferably with a photo

**Comment by progzone122** [comment]
> I'm not sure what touch I have. When in lk2nd bootloader, I can see qcom,mdss_dsi_ili7807_fhdplus_video in panel line. Is this a good info?

Yeah, that'll help. We now know what configuration lk2nd is loading. You can find out which touchscreen you have simply by using the free Device HW Info application

![изображение](https://github.com/user-attachments/assets/7c1acfd3-061c-4701-a4aa-4eaf822baba6)

**Comment by otomay** [comment]
it's a goodix too, weird : /

![image](https://github.com/user-attachments/assets/dae06490-fdbe-46db-b25a-aee9c43337fa)

**Comment by progzone122** [comment]
> it's a goodix too, weird : /
> 
> ![image](https://github.com/user-attachments/assets/dae06490-fdbe-46db-b25a-aee9c43337fa)
> 

Look, try to install it all again carefully according to my instructions without skipping a single step. It should work.

**Comment by otomay** [comment]
I'm certain that I followed 100% correct, IDK what is wrong :/

I gave up and installed the console version. Connected a keyboard with otc adapter and turn on ssh.
I did by building the .img files with pmbootstrap and flashing with your guide.

TYSM for your time!

**Comment by progzone122** [comment]
> I'm certain that I followed 100% correct, IDK what is wrong :/
> 
> I gave up and installed the console version. Connected a keyboard with otc adapter and turn on ssh.
> I did by building the .img files with pmbootstrap and flashing with your guide.
> 
> TYSM for your time!

I'm glad my guide helped you =)
